name: wit_niit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # 状态管理、路由管理、国际化、改变主题、中间件
  get: 4.6.5
  #下拉刷新
  pull_to_refresh: ^2.0.0
  #网络请求
  dio: ^4.0.6
  #存储
#  shared_preferences: any
  #获取版本信息
  package_info: any
  #屏幕适配
  flutter_screenutil: ^5.0.0+2
  #加载框
  flutter_easyloading: ^3.0.5
  #Flutter常用工具类库： https://github.com/Sky24n/flustars
  flustars: ^2.0.1
  # 国际化
  intl: ^0.17.0
  #跳转网页
  url_launcher: any
  #拍照、图片选择
  image_picker: any
  #图片预览
  photo_view: ^0.14.0
  #网络加载图
  cached_network_image: any
  #通知权限
  notification_permissions: ^0.6.1



dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - images/public/

