name: wit_niit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # 状态管理、路由管理、国际化、改变主题、中间件
  get: 4.6.5
  #下拉刷新
  pull_to_refresh: ^2.0.0
  #网络请求
  dio: ^4.0.6
  #获取版本信息
  package_info: any
  #屏幕适配
  flutter_screenutil: ^5.0.0+2
  #加载框
  flutter_easyloading: ^3.0.5
  #Flutter常用工具类库： https://github.com/Sky24n/flustars
  flustars: ^2.0.1
  # 国际化
  intl: ^0.17.0
  #跳转网页
  url_launcher: any
  #拍照、图片选择
  images_picker: ^1.2.11
  # https://pub.flutter-io.cn/packages/images_picker
  # https://juejin.cn/post/6886643071069634567
  #图片预览
  photo_view: ^0.14.0
  #网络加载图
  cached_network_image: any
  #通知权限
  notification_permissions: ^0.6.1
  # Authing 身份云
  authing_sdk: ^1.0.0
  # 日历组件
  table_calendar: ^3.0.8
  # fake  https://pub.dev/packages/faker/install
  faker: ^2.0.0
  # 日期时间包
  jiffy: ^5.0.0
  # StreamChannel 通信
  web_socket_channel: ^2.2.0
  # 二维码扫描
  qr_code_scanner: ^1.0.1 # 不支持识别相册图，无动画
  #  flutter_scankit: ^1.2.4 # 安装后 ios 模拟器无法运行和打包
  #日期时间选择器
  flutter_datetime_picker:
  date_format: ^2.0.7
  # 地址选择器
  city_pickers: ^1.1.3
  # emoji
  emoji_picker_flutter: ^1.5.0
  # 生成二维码
  qr_flutter: ^4.0.0
  # 即使通信
  leancloud_official_plugin: ^1.0.1
  # 数据存储
  leancloud_storage: ^0.7.10

  # 百度地图
  flutter_bmflocation: ^3.3.0
  flutter_baidu_mapapi_map: ^3.0.0+2
  flutter_baidu_mapapi_search: ^3.0.0
  # 权限请求
  permission_handler: ^10.2.0
  # 视频播放
  video_player: ^2.4.8



dev_dependencies: 
  flutter_lints: ^2.0.0
  # 启动画面
  flutter_native_splash: ^2.2.10
  # 启动图标
#  flutter_launcher_icons: ^0.11.0
  flutter_test: 
    sdk: flutter
  flutter_ume: ^1.0.1
  flutter_ume_kit_ui: ^1.0.0
  flutter_ume_kit_device: ^1.0.0
  flutter_ume_kit_perf: ^1.0.0
  flutter_ume_kit_show_code: ^1.0.0
  flutter_ume_kit_console: ^1.0.0
  flutter_ume_kit_dio: ^1.0.0

flutter: 
  uses-material-design: true

  assets:
    - images/login/
    - images/public/
    - images/public/emoji.png
    - images/public/folder.png
    - images/public/jksb.png
    - images/public/kcb.png
    - images/public/ngzx.png
    - images/public/picture.png
    - images/public/qrcode.png
    - images/public/rc.png
    - images/public/skzb.png
    - images/public/tw.png
    - images/public/tzgg.png
    - images/public/voice.png
    - images/public/wlbz.png
    - images/public/wp.png
    - images/public/xl.png
    - images/public/xsqj.png
    - images/public/xywj.png
    - images/public/xyyx.png
    - images/public/zhjs.png
    - images/public/zhrx.png
    - images/school/
    - images/contacts/

  fonts:
    - family: iconfont
      fonts:
        - asset: fonts/iconfont.ttf


flutter_native_splash:
  background_image: images/login/wit_niit.png
  android_12:
    image: images/login/wit_niit.png
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "images/public/emoji.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21 # android min sd